#!/bin/bash

help() {
  echo "Usage:"
  echo "  zmicro package install you-get <args...>"
  echo ""
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  which you-get >>/dev/null 2>&1
  if [ "$?" != "0" ]; then
    pm install -y you-get
  fi

  log::success "install you-get success."
}

run() {
  core $@
}

run $@
